# Force IPv4-only resolution via Cloudflare DNS
# We need to set IPv6 off otherwise Nginx tries to use IPv6 to contact the upstream server
resolver 1.1.1.2 1.0.0.2 ipv6=off;

# Proxy settings
proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=my_cache:10m max_size=100g
inactive=182d use_temp_path=off;

upstream mirrorservice {
    server www.mirrorservice.org:443;
    keepalive 16;
}

server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name  _;

    # Send requests for the /tools/ directory to a path on disk so we can serve some local tools from this server like
    # ISOs and such for netbooting.
    location /tools/ {
        # (Remember the actual path here will end up being /var/www/localhost/htdocs/tools/ on disk)
        root                            /var/www/localhost/htdocs;
        autoindex                       on;
    }

    # Proxy requests for known package files under /sites/ to the Kent Uni upstream (and also cache them on disk)
    # (.img is needed to cache netboot files for Fedora in particular since the netboot process mostly involves loading a large 'install.img' file)
    location ~* \/sites\/.*\.(rpm|drpm|img|deb|apk)$ {
        proxy_pass                      https://mirrorservice;
        proxy_set_header                Host www.mirrorservice.org;

        # This needs to be enabled or Nginx doesn't end up caching anything properly
        proxy_buffering                 on;

        proxy_cache                     my_cache;
        proxy_cache_background_update   on;
        proxy_cache_lock                on;
        proxy_cache_revalidate          on;

        # Fix timeout errors
        # https://stackoverflow.com/a/54605107
        proxy_http_version 1.1;
        proxy_set_header Connection "";

        # Deliver stale content if any of the errors below are reached (timeout, HTTP 50x, etc)
        proxy_cache_use_stale           error timeout updating http_500 http_502 http_503 http_504;

        # Ignore Cache-Control headers from upstream and cache for a max of 182 days (valid requests only).
        proxy_cache_valid 200 206       182d;
        proxy_ignore_headers            Cache-Control;

        # File must be fetched a minimum of 1 time before Nginx will cache it.
        proxy_cache_min_uses            1;
    }

    # Proxy most requests to the /sites/ subdirectory directly to the Kent Uni upstream (without caching)
    location /sites/ {
        proxy_pass                      https://mirrorservice;
        proxy_set_header                Host www.mirrorservice.org;
    }
}
