# Based on the corerad.toml upstream reference file here:
#   https://github.com/mdlayher/corerad/blob/main/internal/config/reference.toml

[[interfaces]]
names = ["vlan190", "vlan191", "vlan193", "vlan194", "vlan195", "vlan201"]
advertise = true

  # Advertise an on-link, autonomous prefix for all /64 addresses on eth0. This
  # also enables stateless address autoconfiguration (SLAAC) for clients.
  [[interfaces.prefix]]

  # Serve route information for IPv6 routes destined to the loopback interface.
  [[interfaces.route]]

  # Inform clients of a recursive DNS server running on this interface.
  [[interfaces.rdnss]]
  ## RDNSS entries configured to last 1 week, as per conversation with Jen Linkova (Google)
  ## about a bug on macOS/iOS related to this expiring while hosts are asleep
  ##
  ## I had hoped that this would be fixed by this PR in Oct 2024, but it doesn't
  ## seem that was the case unfortunately. Perhaps a future PR will fix it fully.
  ## See: https://github.com/mdlayher/corerad/pull/48
  lifetime = "604800s"

  # Specify a NDS DNS Search List
  [[interfaces.dnssl]]
  domain_names = ["home.arpa"]

  [[interfaces.pref64]]
  ## Send AAISP NAT64 prefix if we're on AAISP in the UK and want to use their upstream NAT64
  ## If we comment this out then much like Unbound does, Corerad will also just default to using
  ## the well-known NAT64 prefix of 64:ff9b::/96
  #prefix = "2001:8b0:6464:0:66::/96"
