# https://github.com/mdlayher/corerad/blob/main/internal/config/reference.toml

[[interfaces]]
names = ["vlan701", "vlan702", "vlan709", "vlan703", "vlan705", "vlan999"]
advertise = true

  # Prefix: attaches a NDP Prefix Information option to the router
  # advertisement.
  [[interfaces.prefix]]

  # Route: attaches an NDP Route Information option to the router advertisement.
  [[interfaces.route]]

  # RDNSS: attaches a NDP Recursive DNS Servers option to the router
  # advertisement.
  [[interfaces.rdnss]]

  # DNSSL: attaches a NDP DNS Search List option to the router advertisement.
  [[interfaces.dnssl]]
  # The maximum time these DNSSL domain names may be used for name resolution.
  # An empty string or 0 means these search domains should no longer be used.
  # "auto" will compute an optimal default. "infinite" means these search
  # domains should be used forever.
  lifetime = "auto"
  domain_names = ["home.arpa"]
