stages:
  - build
  - prep
  - release

image-build-rpi4:
  image: quay.io/podman/stable:latest
  stage: build
  timeout: 3h  # Extend timeout as we're building for non-native architectures
  before_script:
    # Login to the GitLab Registry
    - podman login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    # Build arm64 image
    - podman build --arch=arm64 -f Dockerfile_image -t $CI_REGISTRY_IMAGE:rpibuild .
    - podman push $CI_REGISTRY_IMAGE:rpibuild
    # Create output directory and then run the container we built, which will output our built Pinewall .tar.gz into the output dir
    - mkdir -p output
    - podman run --arch=arm64 --rm -v "$(pwd)/output:/tmp/output" $CI_REGISTRY_IMAGE:rpibuild
    # Build the .tar.gz into an .img.gz (requires privileges to mount loop devices)
    #- podman run --arch=arm64 --rm --privileged -v "$(pwd)/output:/tmp/output" --entrypoint ./imagepack.sh $CI_REGISTRY_IMAGE:rpibuild  # TODO
    # Show the contents of our output directory, and then move the image so we can make it available as an artefact with GitLab CI
    - ls -lah output
    #- mv -fv output/pinewall.img.gz $CI_PROJECT_DIR/pinewall.img.gz  # TODO
    - mv -fv output/pinewall.tar.gz $CI_PROJECT_DIR/pinewall.tar.gz
  artifacts:
    paths:
      # Relative to the project directory ($CI_PROJECT_DIR) so we need the mv command at the end of the script above for this to work
      #- pinewall.img.gz  # TODO
      - pinewall.tar.gz
    expire_in: 1 day

image-build-x86:
  image: quay.io/podman/stable:latest
  stage: build
  before_script:
    - podman login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  # Default branch leaves tag empty (= latest tag)
  # All other branches are tagged with the escaped branch name (commit ref slug)
  script:
    # Build x86_64 image
    - podman build --pull -f Dockerfile_image -t $CI_REGISTRY_IMAGE:imagebuild .
    - podman push "$CI_REGISTRY_IMAGE:imagebuild"
    # Create output directory and then run the container we built, which will output our built Pinewall .iso into the output dir
    - mkdir -p output
    - podman run --rm -v "$(pwd)/output:/tmp/output" $CI_REGISTRY_IMAGE:imagebuild
    # Show the contents of our output directory, and then move the image so we can make it available as an artefact with GitLab CI
    - ls -lah output
    - mv -fv output/pinewall.iso $CI_PROJECT_DIR/pinewall.iso
  artifacts:
    paths:
      # Relative to the project directory ($CI_PROJECT_DIR) so we need the mv command in the script above for this to work
      - pinewall.iso
    expire_in: 1 day

overlay-build-noarch:
  image: quay.io/podman/stable:latest
  stage: build
  before_script:
    - podman login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  # Default branch leaves tag empty (= latest tag)
  # All other branches are tagged with the escaped branch name (commit ref slug)
  script:
    # Build image on default arch (it doesn't matter here)
    - podman build --pull -f Dockerfile_overlay -t $CI_REGISTRY_IMAGE:overlaybuild .
    - podman push "$CI_REGISTRY_IMAGE:overlaybuild"

overlay-prep-noarch:
  # Use the Pinewall builder image we just built in the image-dep stage above
  image: $CI_REGISTRY_IMAGE:overlaybuild
  stage: prep
  script:
    - mkdir /tmp/overlays
    - /genapkovl-pinewall.sh
    - mv -fv /tmp/overlays/pinewall.apkovl.tar.gz $CI_PROJECT_DIR/pinewall.apkovl.tar.gz
  artifacts:
    paths:
      # Relative to the project directory ($CI_PROJECT_DIR) so we need the mv command in the script above for this to work
      - pinewall.apkovl.tar.gz
    expire_in: 1 day

publish-artifacts:
  image: docker.io/curlimages/curl:latest
  stage: release
  # Keep all the untracked files generated by the build stages since this is where our actual ISO and apkoverlay files ended up
  dependencies: 
    - image-build-rpi4
    - image-build-x86
    - overlay-prep-noarch
  script:
    - |
      DATECODE=$(date "+%Y%m%d-%H%M")
      curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file ${CI_PROJECT_DIR}/pinewall.iso "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/Pinewall/${DATECODE}/pinewall-x86_64-${DATECODE}.iso"
      curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file ${CI_PROJECT_DIR}/pinewall.tar.gz "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/Pinewall/${DATECODE}/pinewall-rpi4-${DATECODE}.tar.gz"
      curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file ${CI_PROJECT_DIR}/pinewall.apkovl.tar.gz "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/Pinewall/${DATECODE}/pinewall.apkovl.tar.gz"
  only:
    refs:
      - master  # Only run the actual upload stage if we're running on the master branch
