stages:
  - builders
  - build
  - release

image-dep:
  image: docker:latest  # Use the official docker image
  stage: builders
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  # Default branch leaves tag empty (= latest tag)
  # All other branches are tagged with the escaped branch name (commit ref slug)
  script:
    - docker build --pull -f Dockerfile_image -t $CI_REGISTRY_IMAGE:imagebuild .
    - docker push "$CI_REGISTRY_IMAGE:imagebuild"

overlay-dep:
  image: docker:latest  # Use the official docker image
  stage: builders
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  # Default branch leaves tag empty (= latest tag)
  # All other branches are tagged with the escaped branch name (commit ref slug)
  script:
    - docker build --pull -f Dockerfile_overlay -t $CI_REGISTRY_IMAGE:overlaybuild .
    - docker push "$CI_REGISTRY_IMAGE:overlaybuild"

image-build-x86:
  # Use the Pinewall builder image we just built in the image-dep stage above
  image:
    name: $CI_REGISTRY_IMAGE:imagebuild
    entrypoint: [""]  # Override ENTRYPOINT so we just run the script below
  stage: build
  script: mv -fv /tmp/output/*.iso $CI_PROJECT_DIR/pinewall.iso
  artifacts:
    paths:
      # Relative to the project directory ($CI_PROJECT_DIR) so we need the mv command in the script above for this to work
      - pinewall.iso
    expire_in: 1 day

overlay-build:
  # Use the Pinewall builder image we just built in the image-dep stage above
  image: $CI_REGISTRY_IMAGE:overlaybuild
  stage: build
  script:
    - mkdir /tmp/overlays
    - /genapkovl-pinewall.sh
    - mv -fv /tmp/overlays/pinewall.apkovl.tar.gz $CI_PROJECT_DIR/pinewall.apkovl.tar.gz
  artifacts:
    paths:
      # Relative to the project directory ($CI_PROJECT_DIR) so we need the mv command in the script above for this to work
      - pinewall.apkovl.tar.gz
    expire_in: 1 day

publish-artifacts:
  image: curlimages/curl:latest
  stage: release
  # Keep all the untracked files generated by the build stages since this is where our actual ISO and apkoverlay files ended up
  dependencies: 
    - image-build-x86
    - overlay-build
  script:
    - |
      DATECODE=$(date "+%Y%m%d-%H%M")
      curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file ${CI_PROJECT_DIR}/pinewall.iso "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/Pinewall/${DATECODE}/pinewall-x86_64-${DATECODE}.iso"
      curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file ${CI_PROJECT_DIR}/pinewall.apkovl.tar.gz "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/Pinewall/${DATECODE}/pinewall.apkovl.tar.gz"
  only:
    refs:
      - master  # Only run the actual upload stage if we're running on the master branch
