stages:
  - builder
  - build
  - release

image-dep:
  # Use the official docker image.
  image: docker:latest
  stage: builder
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  # Default branch leaves tag empty (= latest tag)
  # All other branches are tagged with the escaped branch name (commit ref slug)
  script:
    - docker build --pull -f Dockerfile_image_x86 -t $CI_REGISTRY_IMAGE:builder .
    - docker push "$CI_REGISTRY_IMAGE:builder"

image-build:
  # Use the Pinewall builder image we just built in the image-dep stage above
  image: $CI_REGISTRY_IMAGE:builder
  stage: build
  script:
    # Sort script execution privileges
    - chmod +x *.sh
    # Run Pinewall ISO build script inside the builder container
    - ./imagebuild.sh
    # Rename our ISO with the version-specific name to something more generic so we can
    # reference it more easily in the CI release stage
    - mv -fv /tmp/images/alpine-pinewall-*.iso /tmp/images/pinewall.iso

image-push:
  image: curlimages/curl:latest
  stage: release
  # Keep all the untracked files generated by the build stage since this contains our actual ISO
  dependencies: 
    - image-build
  script:
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file /tmp/images/pinewall.iso "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/Pinewall/$(date "+%Y-%m-%d")/pinewall-x86_64-$(date "+%Y-%m-%d").iso"'
  # Only run the actual upload stage if we're running on the master branch
  only:
    refs:
      - master
