#!/usr/bin/env sh
set -eu

case "$1" in
    build)
        # Build image
        mkdir -p "$PWD"/images
        # Mounts a tmpfs in /tmp in the container as this is where
        # Ansible will do our build (ansible.builtin.tempfile)
        podman run --rm -it -v "$PWD":/mnt:z \
            --entrypoint /bin/sh \
            --workdir /mnt \
            --mount="type=tmpfs,tmpfs-size=512M,destination=/tmp" \
            docker.io/library/alpine:latest \
              -c 'apk --no-cache add ansible && \
                ansible-playbook build.yml'
        ;;
    deploy)
        (
        # Start local webserver to host the images we've built for Proxmox to grab
        podman stop allium-image-deploy 2>/dev/null || true
        podman rm allium-image-deploy 2>/dev/null || true
        podman run -d --rm -v "$PWD"/images:/usr/share/nginx/html/images:ro,z \
            --name allium-image-deploy \
            -p 8080:80 \
            docker.io/library/nginx:alpine
        # Discover Proxmox credentials from TPM
        export PROXMOX_VE_USERNAME="root@pam"
        export PROXMOX_VE_PASSWORD="$(sudo tpm2 rsadecrypt -c 0x81010001 ~/.ssh/tpm-$(hostname)/api_key_prox_rtr.enc)"
        # Discover the primary IP of this deployment host
        export TF_VAR_deployment_host_ip="$(ip -4 addr show dev "$(ip route show default | awk '/default/ {print $5}')" | awk '/inet / {print $2}' | cut -d/ -f1)"
        # Deploy using OpenTofu
        cd "$PWD/terraform"
        podman run -it --rm -v "$PWD":/mnt:z \
            --env PROXMOX_VE_USERNAME \
            --env PROXMOX_VE_PASSWORD \
            --env TF_VAR_deployment_host_ip \
            --workdir /mnt \
            --entrypoint /bin/sh \
            ghcr.io/opentofu/opentofu:latest -c \
              'tofu init && tofu fmt && tofu apply'
        # Stop local webserver container
        podman stop allium-image-deploy || true
        )
        ;;
    "")
        echo "Usage: $0 <subcommand>"
        echo
        echo "Subcommands:"
        echo "  build    - Build Tor Relay images"
        echo "  deploy   - Deploy Relay images to Proxmox"
        ;;
    *)
        echo "Error: Unknown subcommand '$1'"
        exit 1
        ;;
esac
