FROM docker.io/alpine:3.14

# Bind mount a directory into /tmp/images when running this image to output a built iso into it

####################################
#  _____ _   ___     __ __     ___    ____  ____  
# | ____| \ | \ \   / / \ \   / / \  |  _ \/ ___| 
# |  _| |  \| |\ \ / /   \ \ / / _ \ | |_) \___ \ 
# | |___| |\  | \ V /     \ V / ___ \|  _ < ___) |
# |_____|_| \_|  \_/       \_/_/   \_\_| \_\____/ 
#                                                 
####################################

# Do not include a trailing slash in repo URL
# Note that not all mirrors mirror all architectures
ENV ALPINEREPO=https://dl-cdn.alpinelinux.org/alpine
ENV ALPINEVER=3.14

ENV PROFILENAME=pinewall_x86
ENV TARGETARCH=x86_64

####################################

RUN apk --no-cache add \
  alpine-conf \
  alpine-sdk \
  apk-tools \
  build-base \
  busybox \
  doas \
  dosfstools \
  fakeroot \
  grub-efi \
  mtools \
  squashfs-tools \
  syslinux \
  tzdata \
  xorriso

# We can't use the build/builder user that most examples use because
# then it can't access the pseudo device that xorriso creates during
# the ISO build process:
#     https://stackoverflow.com/a/58297342
RUN addgroup root abuild

RUN mkdir /tmp/abuild
WORKDIR /tmp/abuild

RUN abuild-keygen -i -a -n

RUN git clone https://gitlab.alpinelinux.org/alpine/aports.git

RUN chmod +x /tmp/abuild/aports/scripts/mkimage.sh

WORKDIR /tmp/abuild/aports/scripts

RUN mkdir /tmp/images

# Add our custom profile
COPY mkimg.$PROFILENAME.sh /tmp/abuild/aports/scripts/mkimg.$PROFILENAME.sh
RUN chmod +x /tmp/abuild/aports/scripts/mkimg.$PROFILENAME.sh

# Add our image building script to the container
COPY imagebuild.sh /tmp/abuild/aports/scripts/imagebuild.sh
RUN chmod +x /tmp/abuild/aports/scripts/imagebuild.sh

# Add in all our configs
COPY etc/ /tmp/etc/

# Run an APK update so we have a recent cache in the Docker image
# (if we don't do this then the "apk fetch" stages of the build that fetch packages
# like the Raspberry Pi bootloader will fail).
RUN apk update
