FROM docker.io/library/alpine:edge as builder

# Bind mount a directory into /tmp/output when running this image
# to output a built image into it

# Copy our env vars into the container
COPY settings.sh /settings.sh

RUN apk --no-cache add \
  alpine-conf \
  alpine-sdk \
  apk-tools \
  build-base \
  busybox \
  dosfstools \
  fakeroot \
  grub-efi \
  mtools \
  squashfs-tools \
  sudo \
  tzdata \
  xorriso

# We can't use the build/builder user that most examples use because
# then it can't access the pseudo device that xorriso creates during
# the ISO build process:
#     https://stackoverflow.com/a/58297342
RUN addgroup root abuild

RUN mkdir /tmp/abuild
WORKDIR /tmp/abuild

# We still need to layer the sudo package into this builder image
# instead of doas, as abuild-keygen expects it to be there
RUN abuild-keygen -i -a -n

# Clone the aports repo for our specific branch
RUN source /settings.sh && git clone --branch "$ALPINEGIT" https://gitlab.alpinelinux.org/alpine/aports.git

RUN chmod +x /tmp/abuild/aports/scripts/mkimage.sh

WORKDIR /tmp/abuild/aports/scripts

RUN mkdir /tmp/images

# Add our custom profiles
COPY mkimg.pinewall_rpi.sh /tmp/abuild/aports/scripts/mkimg.pinewall_rpi.sh
COPY mkimg.pinewall_x86.sh /tmp/abuild/aports/scripts/mkimg.pinewall_x86.sh
RUN chmod +x /tmp/abuild/aports/scripts/mkimg.*.sh

# Add our image building script to the container
COPY imagebuild.sh /tmp/abuild/aports/scripts/imagebuild.sh
RUN chmod +x /tmp/abuild/aports/scripts/imagebuild.sh

# Add in all our configs
COPY etc/ /tmp/etc/
COPY var /tmp/var

# Run an APK update so we have a recent cache ready in the Docker image
# (if we don't do this then the "apk fetch" stages of the build that fetch
# packages like the Raspberry Pi bootloader will fail).
RUN apk update

# Build our image
RUN source /settings.sh && ./imagebuild.sh

# Move our image to a better-named location
RUN source /settings.sh && mv -fv "/tmp/images/alpine-$PROFILENAME-$ALPINETAG-$(uname -m).iso" /tmp/images/pinewall.iso || true
RUN source /settings.sh && mv -fv "/tmp/images/alpine-$PROFILENAME-$ALPINETAG-$(uname -m).tar.gz" /tmp/images/pinewall.tar.gz || true

# List our image directory
RUN ls -lah /tmp/images

# Copy our built image into a new container
FROM docker.io/library/ubuntu:20.04

# Install dosfstools so we can make VFAT filesystems
RUN apt-get update && apt-get install -y dosfstools

# Copy our built images and settings from the build container
COPY --from=builder /tmp/images /tmp/images
COPY --from=builder /settings.sh /settings.sh

COPY imagepack.sh /opt/imagepack.sh

# Add in our Pi firmware tweaks
COPY usercfg.txt /opt/usercfg.txt

WORKDIR /opt

# Just in case we run this in CI instead of bind-mounting
# the /tmp/output directory inside, we'll try and create
# this directory
RUN mkdir -p /tmp/output

# When we run the container, copy what we've built into the directory we will
# mount at runtime as /tmp/output
#
# We don't enclose this in [""] because if we leave it like this then it gets
# run in the context of a shell and we can use the wildcard
ENTRYPOINT cp -Rfv /tmp/images/* /tmp/output/
