FROM docker.io/library/alpine:3.15 as builder

# Bind mount a directory into /tmp/output when running this image
# to output a built image into it

# Copy our env vars into the container
COPY settings.sh /settings.sh

RUN apk --no-cache add \
  alpine-conf \
  alpine-sdk \
  apk-tools \
  build-base \
  busybox \
  dosfstools \
  fakeroot \
  grub-efi \
  mtools \
  squashfs-tools \
  sudo \
  tzdata \
  xorriso

# We can't use the build/builder user that most examples use because
# then it can't access the pseudo device that xorriso creates during
# the ISO build process:
#     https://stackoverflow.com/a/58297342
RUN addgroup root abuild

RUN mkdir /tmp/abuild
WORKDIR /tmp/abuild

# We still need to layer the sudo package into this builder image
# instead of doas, as abuild-keygen expects it to be there
RUN abuild-keygen -i -a -n

# Clone the aports repo for our specific branch
RUN source /settings.sh && git clone --branch "$ALPINEVER-stable" https://gitlab.alpinelinux.org/alpine/aports.git

RUN chmod +x /tmp/abuild/aports/scripts/mkimage.sh

WORKDIR /tmp/abuild/aports/scripts

RUN mkdir /tmp/images

# Add our custom profiles
COPY mkimg.pinewall_rpi.sh /tmp/abuild/aports/scripts/mkimg.pinewall_rpi.sh
COPY mkimg.pinewall_x86.sh /tmp/abuild/aports/scripts/mkimg.pinewall_x86.sh
RUN chmod +x /tmp/abuild/aports/scripts/mkimg.*.sh

# Add our image building script to the container
COPY imagebuild.sh /tmp/abuild/aports/scripts/imagebuild.sh
RUN chmod +x /tmp/abuild/aports/scripts/imagebuild.sh

# Add in all our configs
COPY etc/ /tmp/etc/
COPY var /tmp/var

# Run an APK update so we have a recent cache ready in the Docker image
# (if we don't do this then the "apk fetch" stages of the build that fetch
# packages like the Raspberry Pi bootloader will fail).
RUN apk update

# Build our image
RUN source /settings.sh && ./imagebuild.sh

# Copy our built image into a new container
FROM docker.io/library/alpine:3.15
COPY --from=builder /tmp/images /tmp/images

# When we run the container, copy what we've built into the output directory
# We don't enclose this in [""] because if we leave it like this then it gets
# run in the context of a shell and we can use the wildcard
CMD cp -Rfv /tmp/images/* /tmp/output/
