FROM docker.io/library/alpine:edge

# Bind mount a directory into /tmp/overlays when running this image
# to output a built overlay into it

# Add some packages that we'll use as sources for overlay data
RUN apk --no-cache add tzdata

# Add our custom APK overlay script
COPY genapkovl-pinewall.sh /genapkovl-pinewall.sh
RUN chmod +x /genapkovl-pinewall.sh

# Add in all our configs
COPY etc/ /tmp/etc/
COPY var/ /tmp/var/
