# /etc/unbound/unbound-localzone.conf

# Define a transparent local zone for our LAN search domain
local-zone: "localdomain." transparent

# You can manually add DNS entries to your local zone here
# I have included some examples below:
local-data-ptr: "10.10.10.10 nextcloud.localdomain"
local-data: "nextcloud.localdomain. A 10.10.10.10"
