# what cipher to use with -e option
# DEFAULT_CIPHER=aes-256-cbc

# Uncomment the row below to encrypt config by default
# ENCRYPTION=$DEFAULT_CIPHER

# TODO:
# This makes the (possibly unsafe) assumption that our disk for
# storing configs will always be /dev/sdb1. Is there a better
# way of doing this?
LBU_MEDIA=sdb1

# Set the LBU_BACKUPDIR variable in case you prefer to save the apkovls
# in a normal directory instead of mounting an external media.
# LBU_BACKUPDIR=/root/config-backups

# Uncomment below to let lbu make up to 3 backups
# BACKUP_LIMIT=3
