# [VLAN 190] Green
interface vlan190 {
  # A flag indicating whether or not the interface is ignored if it does not exist at start-up. By default, radvd exits.
  # Default: off
  IgnoreIfMissing on;

  # A flag indicating whether or not the router sends periodic router advertisements and responds to router solicitations.
  # Default: off
  AdvSendAdvert on;

  # Configure prefix to be used for this VLAN
  # Using ::64 will allow radvd to auto-detect the prefix from the IPs on the interface
  prefix ::/64 {
  };

  # Tell clients about our NAT64 prefix as per PREF64 spec (RFC 8781)
  # (DISABLED) - Need to wait for a new radvd release to make use of this feature
  #nat64prefix 2001:8b0:6464:0:66::/96 {
  #};

  # Configure DNS servers for devices on this network
  RDNSS 2001:4860:4860::8888 2001:4860:4860::8844 {
    # Make sure RDNSS entries do not expire while device is asleep
    # (works around bug on Apple devices which should be fixed during
    # the Sonoma release cycle)
    AdvRDNSSLifetime 604800;
  };
};
