# Configure search domain
search home.arpa

# Andrews & Arnold customer facing DNS servers.
#
# These are only used for host-level DNS
# resolution. The DNS servers passed out via
# DHCP are configured elsewhere -
# in the dhcpd config for IPv4 clients, and in
# the radvd config for IPv6 clients.
#
# These are only available to A&A clients.
nameserver 2001:8b0::2020
nameserver 2001:8b0::2021
nameserver 217.169.20.20
nameserver 217.169.20.21
