#!/bin/sh
#
# This script is run by pppd when there's a successful ppp connection.
#

# Restart chronyd on successful ppp connection, to force an NTP sync
# this is important if we're on a Pi without an RTC.
/sbin/rc-service chronyd restart

# Sleep for 3 seconds
sleep 3

# Restart unbound on successful ppp connection too, as I've had issues
# with it failing when using a DoT upstream when the clock isn't synced
# yet.
/sbin/rc-service unbound restart
