# /etc/dhcp/dhcpd-ranges.conf

# Example Subnet 1
#  - Subnet:      10.10.10.0/24
#  - DHCP Range:  10.10.10.100 - 10.10.10.200
#  - TFTP Server: 10.10.10.1
subnet 10.10.10.0 netmask 255.255.255.0 {
  range 10.10.10.100 10.10.10.200;
  option broadcast-address 10.10.10.255;
  option domain-name "localdomain";
  option domain-name-servers 10.10.10.1;
  option routers 10.10.10.1;
  option time-servers 10.10.10.1;

  # If PXE client is running UEFI, assume this is
  # a Secure Boot system and serve our signed
  # UEFI shim. Otherwise, if this is a legacy BIOS
  # client then serve the netboot.xyz installer.
  next-server 10.10.10.1;
  if option arch = 00:07 {
    filename "shimx64.efi";
  } else {
    filename "netboot.xyz.kpxe";
  }
}

# Example Subnet 2
#  - Subnet:      10.2.0.0/24
#  - DHCP Range:  10.2.0.100 - 10.2.0.200
subnet 10.2.0.0 netmask 255.255.255.0 {
  range 10.2.0.100 10.2.0.200;
  option broadcast-address 10.2.0.255;
  option domain-name "localdomain";
  option domain-name-servers 10.2.0.1;
  option routers 10.2.0.1;
  option time-servers 10.2.0.1;
}
