# Enable IPv4 forwarding
net.ipv4.ip_forward = 1

# Enable IPv6 Forwarding
net.ipv6.conf.all.forwarding = 1

# Log martian packets to dmesg
net.ipv4.conf.all.log_martians = 1
net.ipv4.conf.default.log_martians = 1

# Enable strict reverse path filtering (drops martians)
net.ipv4.conf.all.rp_filter = 1
net.ipv4.conf.default.rp_filter = 1
